const phraseMap: Array<[string, string]> = [
  ['Back To Home', 'Volver al inicio'],
  ['All rights reserved.', 'Todos los derechos reservados.'],
  ['Business Outcomes', 'Resultados de negocio'],
  ['Capabilities', 'Capacidades'],
  ['Screens', 'Pantallas'],
  ['Flow', 'Flujo'],
  ['Close', 'Cerrar'],
  ['AP Volume', 'Volumen AP'],
  ['Outstanding', 'Pendientes'],
  ['Aging Risk', 'Riesgo de antigüedad'],
  ['Cash Match', 'Conciliación bancaria'],
  ['Audit Trail', 'Trazabilidad de auditoría'],
  ['AR Volume', 'Volumen AR'],
  ['Open AR', 'AR abierta'],
  ['DSO Risk', 'Riesgo de DSO'],
  ['Top Customers', 'Clientes principales'],
  ['Fixed Assets Governance Across The Full Asset Lifecycle', 'Gobernanza de activos fijos en todo el ciclo de vida del activo'],
  ['EPIX Fixed Assets controls acquisition, categorization, depreciation, transfers, retirement, and reconciliation against accounting books.', 'EPIX Activos fijos controla adquisición, categorización, depreciación, transferencias, baja y conciliación con libros contables.'],
  ['Asset category, location, and method setup.', 'Configuración de categoría, ubicación y método del activo.'],
  ['Depreciation schedule and execution controls.', 'Controles de programación y ejecución de la depreciación.'],
  ['Acquisition and transaction lifecycle tracking.', 'Seguimiento del ciclo de vida de adquisiciones y transacciones.'],
  ['Transfer, retirement, and disposal workflows.', 'Flujos de transferencia, baja y disposición.'],
  ['Asset-to-account reconciliation and reporting.', 'Conciliación activo-cuenta e informes.'],
  ['Asset Lifecycle Flow', 'Flujo del ciclo de vida del activo'],
  ['Register and classify asset', 'Registrar y clasificar activo'],
  ['Assign location and depreciation rules', 'Asignar ubicación y reglas de depreciación'],
  ['Run periodic depreciation', 'Ejecutar depreciación periódica'],
  ['Execute transfer or retirement actions', 'Ejecutar acciones de transferencia o baja'],
  ['Reconcile with accounting records', 'Conciliar con registros contables'],
  ['Fixed Assets Screens', 'Pantallas de activos fijos'],
  ['Accurate asset valuation', 'Valoración precisa de activos'],
  ['Stronger compliance evidence', 'Evidencia de cumplimiento reforzada'],
  ['Better capital planning decisions', 'Mejores decisiones de planificación de capital'],
  ['Financial backbone for journal governance, posting discipline, and multi-currency reporting.', 'Columna vertebral financiera para la gobernanza de asientos, disciplina contable e informes multidivisa.'],
  ['Currency & exchange-rate governance', 'Gobernanza de moneda y tipo de cambio'],
  ['Banking and liquidity control through statement processing, matching, reconciliation, and transfers.', 'Control bancario y de liquidez mediante procesamiento de extractos, conciliación y transferencias.'],
  ['Controlled handling of business trip advances, petty cash settlements, and expense reconciliation.', 'Gestión controlada de anticipos de viaje, liquidaciones de caja chica y conciliación de gastos.'],
  ['Real-time inventory control across warehouses, receipts, issues, returns, and on-hand visibility.', 'Control de inventario en tiempo real entre almacenes, entradas, salidas, devoluciones y visibilidad de existencias.'],
  ['End-to-end asset lifecycle control from acquisition to depreciation, transfer, and retirement.', 'Control integral del ciclo de vida de activos, desde la adquisición hasta la depreciación, transferencia y baja.'],
  ['Asset category and method setup', 'Configuración de categoría y método de activo'],
  ['Asset category & method setup', 'Configuración de categoría y método de activo'],
  ['Depreciation scheduling and execution', 'Programación y ejecución de la depreciación'],
  ['Depreciation scheduling', 'Programación de la depreciación'],
  ['Production planning and execution controls for orders, inspections, packing, and progress visibility.', 'Controles de planificación y ejecución de producción para órdenes, inspecciones, empaque y visibilidad del avance.'],
  ['Inspection operations management with quality standards, pricing controls, and productivity reporting.', 'Gestión de operaciones de inspección con estándares de calidad, controles de precios e informes de productividad.'],
  ['Configurable approval chains, escalation rules, and SLA monitoring built in.', 'Cadenas de aprobación configurables, reglas de escalamiento y monitoreo de SLA integrados.'],
  ['Role-Based Access Control', 'Control de acceso basado en roles'],
  ['Modular Architecture', 'Arquitectura modular'],
  ['Control across warehouses', 'Control entre almacenes'],
  ['Pricing controls, and productivity', 'Controles de precios y productividad'],
  ['Secure Login & Access', 'Inicio de sesión y acceso seguros'],
  ['Master Data Governance', 'Gobernanza de datos maestros'],
  ['Master Data Flow', 'Flujo de datos maestros'],
  ['Master Data', 'Datos maestros'],
  ['Requisition', 'Requisición'],
  ['Purchase Order', 'Orden de compra'],
  ['Goods Receipt', 'Recepción de mercancía'],
  ['Reports', 'Informes'],
  ['Daily boards', 'Tableros diarios'],
  ['Professional Services', 'Servicios profesionales'],
  ['Manufacturing', 'Manufactura'],
  ['Smart Visual Flows', 'Flujos visuales inteligentes'],
  ['See Real End-To-End Business Execution', 'Visualiza la ejecución real de negocio de punta a punta'],
  ['Open Related Screenshot', 'Abrir captura relacionada'],
  ['Industry Solutions', 'Soluciones por industria'],
  ['Configured For Sector-Specific Operations', 'Configurado para operaciones específicas por sector'],
  ['Order To Cash', 'De pedido a cobro'],
  ['Hire To Retire', 'De contratación a retiro'],
  ['Supplier Liability Control', 'Control de pasivos de proveedores'],
  ['Receivable Performance', 'Rendimiento de cuentas por cobrar'],
  ['HR And Payroll Governance', 'Gobernanza de RR. HH. y nómina'],
  ['Workforce View', 'Vista de fuerza laboral'],
  ['Employee Claims', 'Reclamaciones de empleados'],
  ['Payroll Posting', 'Registro de nómina'],
  ['Track Receivable Throughput', 'Seguimiento del volumen de cuentas por cobrar'],
  ['Focus On Open Balances', 'Enfoque en saldos abiertos'],
  ['Control Aging Buckets', 'Control de tramos de antigüedad'],
  ['Prioritize Key Accounts', 'Priorizar cuentas clave'],
  ['Capture Payables Volume', 'Capturar volumen de cuentas por pagar'],
  ['Prioritize Open Liabilities', 'Priorizar pasivos abiertos'],
  ['Control Aging Exposure', 'Controlar exposición por antigüedad'],
  ['Match Bank Activity', 'Conciliar actividad bancaria'],
  ['Post To General Ledger', 'Registrar en libro mayor'],
  ['Monitor Workforce Health', 'Monitorear salud de la fuerza laboral'],
  ['Settle Claims And Advances', 'Liquidar reclamaciones y anticipos'],
  ['Post Payroll To GL', 'Registrar nómina en GL'],
  ['Workflow Timeline', 'Línea de tiempo del flujo de trabajo'],
  ['Flow Timeline', 'Línea de tiempo del flujo'],
  ['Approve And Continue', 'Aprobar y continuar'],
  ['Next Planned Pages', 'Próximas páginas planificadas'],
  ['Optimized For SMB Finance Teams', 'Optimizado para equipos financieros PyME'],
  ['Detailed AP Capabilities', 'Capacidades detalladas de AP'],
  ['Order To Collection Flow', 'Flujo de pedido a cobro'],
  ['Business Flow: Procure To Pay (AP Control Layer)', 'Flujo de negocio: de compra a pago (capa de control AP)'],
  ['Why This AP Page Matters For ERP Buyers', 'Por qué esta página de AP importa a compradores de ERP'],
  ['Request AP Demo', 'Solicitar demo de AP'],
  ['See AP Flow', 'Ver flujo de AP'],
  ['Manual Process', 'Proceso manual'],
  ['Real-Time', 'Tiempo real'],
  ['Full Audit', 'Auditoría completa'],
  ['Accounts Receivable For Faster Collection And Revenue Visibility', 'Cuentas por cobrar para una cobranza más rápida y mayor visibilidad de ingresos'],
  ['Accounts Receivable Capabilities', 'Capacidades de cuentas por cobrar'],
  ['Outstanding Receivables', 'Cuentas por cobrar pendientes'],
  ['Receivable Volume Summary', 'Resumen del volumen de cuentas por cobrar'],
  ['Receivable Aging Analysis', 'Análisis de antigüedad de cuentas por cobrar'],
  ['Visibility into AR transaction throughput.', 'Visibilidad del volumen transaccional de AR.'],
  ['Outstanding balances segmented for action.', 'Saldos pendientes segmentados para acción.'],
  ['Aging risk view to improve DSO performance.', 'Vista de riesgo por antigüedad para mejorar el desempeño del DSO.'],
  ['Inspection Transaction Grid', 'Cuadrícula de transacciones de inspección'],
  ['Inspection KPI Analytics', 'Analítica de KPI de inspección'],
  ['Inspection Workspace Access', 'Acceso al espacio de trabajo de inspección'],
  ['Line-level tracking of inspection transactions.', 'Seguimiento a nivel de línea de transacciones de inspección.'],
  ['Visualization of quality and productivity metrics.', 'Visualización de métricas de calidad y productividad.'],
  ['Unified navigation for daily inspection operations.', 'Navegación unificada para operaciones diarias de inspección.'],
  ['Fixed Assets Dashboard', 'Panel de activos fijos'],
  ['Asset Accounting Linkage', 'Vínculo contable de activos'],
  ['Depreciation Analytics', 'Analítica de depreciación'],
  ['Executive indicators for asset lifecycle governance.', 'Indicadores ejecutivos para la gobernanza del ciclo de vida de activos.'],
  ['Posting and reconciliation continuity with GL.', 'Continuidad de registro y conciliación con GL.'],
  ['Visualization of depreciation and book-value trends.', 'Visualización de tendencias de depreciación y valor en libros.'],
  ['Master Navigation Hub', 'Centro de navegación maestra'],
  ['Reference Data Grid', 'Cuadrícula de datos maestros'],
  ['Master Governance Planning', 'Planificación de gobernanza maestra'],
  ['Fast access to reference maintenance workspaces.', 'Acceso rápido a espacios de mantenimiento de datos maestros.'],
  ['Bulk maintenance for master records with filtering and controls.', 'Mantenimiento masivo de registros maestros con filtros y controles.'],
  ['Planning and follow-up for data standardization programs.', 'Planificación y seguimiento de programas de estandarización de datos.'],
  ['Bank Statement Upload', 'Carga de estado de cuenta bancario'],
  ['Cash Operations Control', 'Control de operaciones de caja'],
  ['Liability And Cash Alignment', 'Alineación de pasivos y caja'],
  ['Fast ingestion of statement files for reconciliation.', 'Carga rápida de archivos de estado de cuenta para conciliación.'],
  ['Operational oversight for disbursement and cash activity.', 'Supervisión operativa de desembolsos y actividad de caja.'],
  ['Visibility to coordinate payable commitments with cash plans.', 'Visibilidad para coordinar compromisos por pagar con planes de caja.'],
  ['Production Gantt Planning', 'Planificación Gantt de producción'],
  ['Order Execution Grid', 'Cuadrícula de ejecución de órdenes'],
  ['Manufacturing Workspace', 'Espacio de trabajo de manufactura'],
  ['Timeline control for production orders and milestones.', 'Control de cronograma para órdenes de producción e hitos.'],
  ['Detailed tracking of order lines and process progress.', 'Seguimiento detallado de líneas de orden y avance del proceso.'],
  ['Unified operational access for planners and shop-floor teams.', 'Acceso operativo unificado para planificadores y equipos de planta.'],
  ['Inventory Executive Summary', 'Resumen ejecutivo de inventario'],
  ['Extended Inventory Summary', 'Resumen ampliado de inventario'],
  ['Inventory Transaction Grid', 'Cuadrícula de transacciones de inventario'],
  ['Operational view of stock health and movement.', 'Vista operativa de salud y movimiento de inventario.'],
  ['Extended metrics for valuation and supply performance.', 'Métricas ampliadas para valorización y desempeño de suministro.'],
  ['Detailed line-level tracking for receipts and issues.', 'Seguimiento detallado por línea para entradas y salidas.'],
  ['HR Executive Dashboard', 'Panel ejecutivo de RR. HH.'],
  ['Employee Transaction Grid', 'Cuadrícula de transacciones de empleados'],
  ['Unified HR Navigation', 'Navegación unificada de RR. HH.'],
  ['Leadership view of workforce and payroll indicators.', 'Vista directiva de indicadores de fuerza laboral y nómina.'],
  ['Detailed operational records for HR transactions.', 'Registros operativos detallados para transacciones de RR. HH.'],
  ['Fast access to attendance, leave, and payroll flows.', 'Acceso rápido a flujos de asistencia, permisos y nómina.'],
  ['Shipment Line Tracking', 'Seguimiento de líneas de envío'],
  ['Shipment Timeline', 'Cronograma de envíos'],
  ['Fulfillment Command View', 'Vista de control de cumplimiento'],
  ['Detailed transaction-level visibility for shipment processing.', 'Visibilidad detallada a nivel transaccional para procesamiento de envíos.'],
  ['Timeline planning for dispatch checkpoints.', 'Planificación cronológica para hitos de despacho.'],
  ['Fast access to shipment and logistics workspaces.', 'Acceso rápido a espacios de trabajo de envíos y logística.'],
  ['ETA Customer Insights', 'Perspectivas ETA de clientes'],
  ['ETA Vendor Insights', 'Perspectivas ETA de proveedores'],
  ['P2P Volume Impact', 'Impacto de volumen de P2P'],
  ['Customer-side ETA trends for compliance and risk review.', 'Tendencias ETA del lado del cliente para revisión de cumplimiento y riesgo.'],
  ['Vendor concentration and submission patterns.', 'Concentración de proveedores y patrones de presentación.'],
  ['Connected payable volumes influenced by ETA flows.', 'Volúmenes por pagar conectados influenciados por flujos ETA.'],
  ['Petty Cash Transactions', 'Transacciones de caja chica'],
  ['Cash Proof Integration', 'Integración de comprobantes de caja'],
  ['Trip And Cash Workspace', 'Espacio de trabajo de viajes y caja'],
  ['Operational control for disbursements and settlement.', 'Control operativo para desembolsos y liquidación.'],
  ['Supporting cash evidence and statement alignment.', 'Soporte de comprobantes de caja y alineación con estados de cuenta.'],
  ['Unified access to request, approve, and settle processes.', 'Acceso unificado para solicitar, aprobar y liquidar procesos.'],
  ['General Ledger', 'Libro mayor'],
  ['Accounts Payable', 'Cuentas por pagar'],
  ['Accounts Receivable', 'Cuentas por cobrar'],
  ['Cash Management', 'Gestión de tesorería'],
  ['Inventory Management', 'Gestión de inventario'],
  ['Human Resources', 'Recursos humanos'],
  ['Fixed Assets', 'Activos fijos'],
  ['Procure To Pay', 'De compra a pago'],
  ['Petty Cash', 'Caja chica'],
  ['Shipment Management', 'Gestión de envíos'],
  ['Discrete Manufacturing', 'Manufactura discreta'],
  ['Business Masters', 'Datos maestros'],
  ['Car Inspection', 'Inspección vehicular'],
  ['Outcomes', 'Resultados'],
  ['vs', 'frente a'],
  ['Vs', 'Frente a'],
  ['real-time', 'en tiempo real'],
  ['workflow', 'flujo de trabajo'],
  ['workflows', 'flujos de trabajo'],
  ['flow', 'flujo'],
  ['flows', 'flujos'],
  ['financial', 'financiero'],
  ['backbone', 'columna vertebral'],
  ['currency', 'moneda'],
  ['exchange-rate', 'tipo de cambio'],
  ['banking', 'bancario'],
  ['liquidity', 'liquidez'],
  ['through', 'mediante'],
  ['controlled', 'controlado'],
  ['handling', 'gestión'],
  ['across', 'entre'],
  ['warehouses', 'almacenes'],
  ['end-to-end', 'de extremo a extremo'],
  ['lifecycle', 'ciclo de vida'],
  ['depreciation', 'depreciación'],
  ['transfer', 'transferencia'],
  ['retirement', 'baja'],
  ['category', 'categoría'],
  ['method', 'método'],
  ['scheduling', 'programación'],
  ['production', 'producción'],
  ['standards', 'estándares'],
  ['pricing', 'precios'],
  ['configurable', 'configurable'],
  ['role-based', 'basado en roles'],
  ['architecture', 'arquitectura'],
  ['secure', 'seguro'],
  ['login', 'inicio de sesión'],
  ['access', 'acceso'],
  ['master', 'maestro'],
  ['data', 'datos'],
  ['requisition', 'requisición'],
  ['purchase', 'compra'],
  ['order', 'orden'],
  ['goods', 'mercancía'],
  ['receipt', 'recepción'],
  ['report', 'informe'],
  ['reports', 'informes'],
  ['daily', 'diario'],
  ['boards', 'tableros'],
  ['manufacturing', 'manufactura'],
  ['professional', 'profesional'],
  ['services', 'servicios'],
  ['rights', 'derechos'],
  ['reserved', 'reservados'],
  ['issue', 'emitir'],
  ['track', 'seguir'],
  ['prioritize', 'priorizar'],
  ['record', 'registrar'],
  ['define', 'definir'],
  ['approve', 'aprobar'],
  ['publish', 'publicar'],
  ['reuse', 'reutilizar'],
  ['audit', 'auditoría'],
  ['ownership', 'propiedad'],
  ['configure', 'configurar'],
  ['capture', 'capturar'],
  ['review', 'revisar'],
  ['focus', 'enfoque'],
  ['monitor', 'monitorear'],
  ['settle', 'liquidar'],
  ['match', 'conciliar'],
  ['post', 'registrar'],
  ['open', 'abierto'],
  ['due', 'vencido'],
  ['claims', 'reclamaciones'],
  ['advances', 'anticipos'],
  ['volume', 'volumen'],
  ['health', 'salud'],
  ['approval', 'aprobación'],
  ['tracking', 'seguimiento'],
  ['reporting', 'informes'],
  ['compliance', 'cumplimiento'],
  ['insights', 'perspectivas'],
  ['executive', 'ejecutivo'],
  ['leadership', 'dirección'],
  ['dashboard', 'tablero'],
  ['dashboards', 'tableros'],
  ['workspace', 'espacio de trabajo'],
  ['workspaces', 'espacios de trabajo'],
  ['grid', 'cuadrícula'],
  ['planning', 'planificación'],
  ['timeline', 'cronograma'],
  ['upload', 'carga'],
  ['statement', 'estado de cuenta'],
  ['disbursement', 'desembolso'],
  ['disbursements', 'desembolsos'],
  ['valuation', 'valorización'],
  ['payroll', 'nómina'],
  ['attendance', 'asistencia'],
  ['leave', 'permiso'],
  ['logistics', 'logística'],
  ['dispatch', 'despacho'],
  ['fulfillment', 'cumplimiento'],
  ['analytics', 'analítica'],
  ['operations', 'operaciones'],
  ['operational', 'operativo'],
  ['finance', 'finanzas'],
  ['supplier', 'proveedor'],
  ['suppliers', 'proveedores'],
  ['customer', 'cliente'],
  ['customers', 'clientes'],
  ['payment', 'pago'],
  ['payments', 'pagos'],
  ['reconciliation', 'conciliación'],
  ['inventory', 'inventario'],
  ['receivable', 'por cobrar'],
  ['receivables', 'cuentas por cobrar'],
  ['payable', 'por pagar'],
  ['payables', 'cuentas por pagar'],
  ['outstanding', 'pendiente'],
  ['aging', 'antigüedad'],
  ['summary', 'resumen'],
  ['shipment', 'envío'],
  ['inspection', 'inspección'],
  ['governance', 'gobernanza'],
  ['visibility', 'visibilidad'],
  ['control', 'control'],
  ['faster', 'más rápido'],
  ['improved', 'mejorado'],
  ['lower', 'menor'],
  ['higher', 'mayor'],
  ['confidence', 'confianza'],
];

const wordMap: Record<string, string> = {
  and: 'y',
  for: 'para',
  with: 'con',
  from: 'desde',
  to: 'a',
  of: 'de',
  in: 'en',
  on: 'en',
  by: 'por',
  under: 'bajo',
  full: 'completo',
  fast: 'rápido',
  speed: 'velocidad',
  quality: 'calidad',
  policy: 'política',
  policies: 'políticas',
  invoice: 'factura',
  invoices: 'facturas',
  collection: 'cobro',
  collections: 'cobros',
  receivable: 'por cobrar',
  receivables: 'cuentas por cobrar',
  payable: 'por pagar',
  payables: 'cuentas por pagar',
  overdue: 'vencido',
  balance: 'saldo',
  balances: 'saldos',
  liability: 'pasivo',
  liabilities: 'pasivos',
  risk: 'riesgo',
  cycle: 'ciclo',
  process: 'proceso',
  processes: 'procesos',
  status: 'estado',
  statuses: 'estados',
  summary: 'resumen',
  summaries: 'resúmenes',
  module: 'módulo',
  modules: 'módulos',
  outstanding: 'pendiente',
  aging: 'antigüedad',
  transaction: 'transacción',
  transactions: 'transacciones',
  throughput: 'volumen',
  monitor: 'monitor',
  monitoring: 'monitoreo',
  approval: 'aprobación',
  approvals: 'aprobaciones',
  routing: 'enrutamiento',
  execution: 'ejecución',
  detailed: 'detallado',
  line: 'línea',
  lines: 'líneas',
  unified: 'unificado',
  metrics: 'métricas',
  evidence: 'comprobantes',
  alignment: 'alineación',
  trend: 'tendencia',
  trends: 'tendencias',
  stock: 'inventario',
  receipts: 'entradas',
  issues: 'salidas',
  employee: 'empleado',
  employees: 'empleados',
  workforce: 'fuerza laboral',
  shipment: 'envío',
  shipments: 'envíos',
  vendor: 'proveedor',
  vendors: 'proveedores',
  request: 'solicitud',
  requests: 'solicitudes',
  settle: 'liquidar',
  settlement: 'liquidación',
  performance: 'desempeño',
};

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function replacePhrase(input: string, from: string, to: string): string {
  const isSingleToken = /^[A-Za-z][A-Za-z-]*$/.test(from);
  const pattern = new RegExp(isSingleToken ? `\\b${escapeRegExp(from)}\\b` : escapeRegExp(from), 'gi');
  return input.replace(pattern, to);
}

function replaceWords(input: string): string {
  return input.replace(/\b[a-zA-Z]{2,}\b/g, (word) => {
    const lower = word.toLowerCase();
    const translated = wordMap[lower];
    if (!translated) return word;
    if (word[0] === word[0].toUpperCase()) {
      return translated[0].toUpperCase() + translated.slice(1);
    }
    return translated;
  });
}

export function moduleSpanishText(input: string): string {
  let out = input;
  const sortedPhrases = [...phraseMap].sort((a, b) => b[0].length - a[0].length);
  for (const [from, to] of sortedPhrases) {
    out = replacePhrase(out, from, to);
  }
  out = replaceWords(out);
  out = out.replace(/\s{2,}/g, ' ').trim();
  out = out.replace(/\bde el\b/gi, 'del').replace(/\ba el\b/gi, 'al');
  return out;
}

export function moduleSpanishObject<T>(value: T): T {
  if (typeof value === 'string') {
    return moduleSpanishText(value) as T;
  }
  if (Array.isArray(value)) {
    return value.map((item) => moduleSpanishObject(item)) as T;
  }
  if (value && typeof value === 'object') {
    const output: Record<string, unknown> = {};
    for (const [key, inner] of Object.entries(value as Record<string, unknown>)) {
      output[key] = moduleSpanishObject(inner);
    }
    return output as T;
  }
  return value;
}
